CREATE EXTENSION pg_trgm;

CREATE TABLE IF NOT EXISTS ari_word (
  id              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  word            VARCHAR(1000) NOT NULL UNIQUE,
  from_dictionary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ari_word_query (
  id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ari_word_id BIGINT NOT NULL UNIQUE REFERENCES ari_word(id),
  query_count BIGINT NOT NULL DEFAULT 1
);
