CREATE EXTENSION pg_trgm;

CREATE TABLE IF NOT EXISTS word (
  id              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  word            VARCHAR(1000) NOT NULL UNIQUE,
  from_dictionary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS word_query (
  id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  word_id     BIGINT NOT NULL UNIQUE REFERENCES word(id),
  query_count BIGINT NOT NULL DEFAULT 1
);
